package nexgougrpc

import (
	"google.golang.org/grpc"

	"github.com/nexgou/server/src/common"
)

// HandlerFunc is the low-level gRPC unary handler signature used internally
// when registering services with the grpc.Server.
type HandlerFunc = grpc.UnaryHandler

// StreamDesc is an alias for grpc.StreamDesc to avoid callers importing grpc directly.
type StreamDesc = grpc.StreamDesc

// ServiceDesc is an alias for grpc.ServiceDesc so callers only import this package.
type ServiceDesc = grpc.ServiceDesc

// ServerStream is an alias for grpc.ServerStream used in streaming handlers.
type ServerStream = grpc.ServerStream

// GRPCRoute binds a gRPC service descriptor to its implementation and optional guards.
// Create one using NewRoute, then chain .Guard() and .Version() as needed.
//
//	nexgougrpc.NewRoute(greeter.Greeter_ServiceDesc, &GreeterController{})
type GRPCRoute struct {
	// Desc is the gRPC ServiceDesc that describes the service methods.
	// This is the value generated by protoc (or hand-written for proto-less usage).
	Desc grpc.ServiceDesc

	// Impl is the concrete struct that implements the service methods.
	// It must satisfy the interface expected by Desc.Handler entries.
	Impl any

	// Guards are evaluated before each unary RPC handler via a UnaryServerInterceptor.
	// Streaming RPCs bypass guards — apply auth via stream.Context() metadata instead.
	Guards []common.Guard

	ver string
}

// NewRoute creates a GRPCRoute that binds desc to impl.
// impl must satisfy all handler signatures referenced in desc.Methods.
//
//	nexgougrpc.NewRoute(greeter.Greeter_ServiceDesc, svcImpl).Guard(&AuthGuard{})
func NewRoute(desc grpc.ServiceDesc, impl any) GRPCRoute {
	return GRPCRoute{Desc: desc, Impl: impl}
}

// Guard attaches one or more guards to every unary RPC in this service.
// Guards run inside a grpc.UnaryServerInterceptor before the handler executes.
// A guard that returns false → codes.PermissionDenied is returned to the client.
// A guard that returns an error → that error is returned as the RPC status.
//
//	nexgougrpc.NewRoute(svc.Desc, impl).Guard(&AuthGuard{}, &RoleGuard{})
func (r GRPCRoute) Guard(guards ...common.Guard) GRPCRoute {
	r.Guards = append(r.Guards, guards...)
	return r
}

// Version sets a metadata tag for this service (informational only — gRPC service
// names cannot be prefixed at the transport level the way HTTP paths can).
// The version is printed in the startup route log.
func (r GRPCRoute) Version(v string) GRPCRoute {
	r.ver = v
	return r
}

// Ver returns the version label.
func (r GRPCRoute) Ver() string { return r.ver }

// GRPCController is implemented by controllers that expose gRPC services.
// A controller can implement both Controller (HTTP routes) and GRPCController
// (gRPC services) simultaneously.
//
// Usage:
//
//	func (c *GreeterController) Register() []nexgou.Route {
//	    return []nexgou.Route{ nexgou.Get("/health", c.Health) }
//	}
//
//	func (c *GreeterController) RegisterGRPC() []nexgougrpc.GRPCRoute {
//	    return []nexgougrpc.GRPCRoute{
//	        nexgougrpc.NewRoute(greeter.Greeter_ServiceDesc, c),
//	    }
//	}
type GRPCController interface {
	RegisterGRPC() []GRPCRoute
}
