// Package nexgou is a high-performance Go framework for building efficient,
// scalable server-side applications, inspired by NestJS.
//
// Users import this single package to access the full public API:
//
//	import nexgou "github.com/nexgou/server"
//
//	func main() {
//	    app := nexgou.CreateApp(AppModule)
//	    app.Listen(":3000")
//	}
package nexgou

import (
	appPkg "github.com/nexgou/server/src/app"
	"github.com/nexgou/server/src/common"
	"github.com/nexgou/server/src/config"
	nexgougrpc "github.com/nexgou/server/src/grpc"
	"github.com/nexgou/server/src/core"
	"github.com/nexgou/server/src/logger"
	nexgousse "github.com/nexgou/server/src/sse"
	nexgouws "github.com/nexgou/server/src/websocket"
)

// ── Type Aliases ──────────────────────────────────────────────────────────────
// All core types are aliased here so callers only import this package.

type (
	// H is a shorthand for map[string]any, used for JSON responses.
	H = common.H

	// Context holds the state of a single HTTP request/response cycle.
	Context = common.Context

	// HandlerFunc is the function signature for all route handlers.
	HandlerFunc = common.HandlerFunc

	// MiddlewareFunc wraps a HandlerFunc to implement middleware.
	MiddlewareFunc = common.MiddlewareFunc

	// Route defines an HTTP route binding (method + path + handler).
	Route = common.Route

	// Controller is implemented by all controllers to register their routes.
	Controller = common.Controller

	// Guard determines whether a request should proceed to the handler.
	Guard = common.Guard

	// Interceptor intercepts execution before and after the handler.
	Interceptor = common.Interceptor

	// Pipe validates and transforms input values before the handler.
	Pipe = common.Pipe

	// ExceptionFilter catches errors and returns structured HTTP responses.
	ExceptionFilter = common.ExceptionFilter

	// IModule is implemented by all Nexgou modules.
	IModule = common.IModule

	// ModuleOptions defines the composition of a module.
	ModuleOptions = common.ModuleOptions

	// HttpException represents a structured HTTP error.
	HttpException = common.HttpException

	// App is the Nexgou application instance.
	App = appPkg.App

	// ── Config ────────────────────────────────────────────────────────────────

	// ConfigService provides typed access to environment variables.
	ConfigService = config.ConfigService

	// ── Logger ────────────────────────────────────────────────────────────────

	// LoggerService is a structured logger injectable via the IoC container.
	LoggerService = logger.LoggerService

	// ScopedLogger is a LoggerService bound to a named context.
	ScopedLogger = logger.ScopedLogger

	// ── WebSocket ─────────────────────────────────────────────────────────────

	// WSContext wraps a WebSocket connection for a single client session.
	WSContext = nexgouws.WSContext

	// WSRoute defines a WebSocket route binding with optional Guards and versioning.
	WSRoute = nexgouws.WSRoute

	// WSController is implemented by controllers that expose WebSocket routes.
	WSController = nexgouws.WSController

	// ── SSE ───────────────────────────────────────────────────────────────────

	// SSEContext holds the state of an active Server-Sent Events stream.
	// Obtain one inside an SSE handler — do not construct directly.
	SSEContext = nexgousse.SSEContext

	// SSEHandlerFunc is the function signature for SSE stream handlers.
	SSEHandlerFunc = nexgousse.HandlerFunc

	// ── gRPC ──────────────────────────────────────────────────────────────────

	// GRPCContext holds the state of a single gRPC RPC call.
	// Passed to Guards that run as UnaryServerInterceptors.
	GRPCContext = nexgougrpc.GRPCContext

	// GRPCRoute binds a gRPC service descriptor to its implementation and guards.
	// Create one using the GRPC() helper or nexgougrpc.NewRoute() directly.
	GRPCRoute = nexgougrpc.GRPCRoute

	// GRPCController is implemented by controllers that expose gRPC services.
	// A controller can implement both Controller (HTTP) and GRPCController (gRPC).
	GRPCController = nexgougrpc.GRPCController

	// GRPCServer wraps *grpc.Server and integrates Nexgou guards.
	GRPCServer = nexgougrpc.GRPCServer

	// GRPCServiceDesc is an alias for grpc.ServiceDesc — the service descriptor
	// generated by protoc or written by hand for proto-less usage.
	GRPCServiceDesc = nexgougrpc.ServiceDesc

	// GRPCServerStream is an alias for grpc.ServerStream used in streaming handlers.
	GRPCServerStream = nexgougrpc.ServerStream
)

// ── Route Helpers ─────────────────────────────────────────────────────────────

// Get creates a GET route binding.
func Get(path string, handler HandlerFunc) Route {
	return Route{Method: "GET", Path: path, Handler: handler}
}

// Post creates a POST route binding.
func Post(path string, handler HandlerFunc) Route {
	return Route{Method: "POST", Path: path, Handler: handler}
}

// Put creates a PUT route binding.
func Put(path string, handler HandlerFunc) Route {
	return Route{Method: "PUT", Path: path, Handler: handler}
}

// Patch creates a PATCH route binding.
func Patch(path string, handler HandlerFunc) Route {
	return Route{Method: "PATCH", Path: path, Handler: handler}
}

// Delete creates a DELETE route binding.
func Delete(path string, handler HandlerFunc) Route {
	return Route{Method: "DELETE", Path: path, Handler: handler}
}

// ── Module ────────────────────────────────────────────────────────────────────

// Module creates a new Nexgou module from the given options.
func Module(opts ModuleOptions) IModule {
	return core.NewModule(opts)
}

// ── Application ───────────────────────────────────────────────────────────────

// CreateApp initializes a new Nexgou application from the root module,
// resolves all dependencies, and registers all controller routes.
func CreateApp(root IModule) *App {
	return appPkg.CreateApp(root)
}

// ── Exception Helpers ─────────────────────────────────────────────────────────

// Exception creates an HTTP exception with a custom status code and message.
func Exception(status int, message string) *HttpException {
	return common.NewHttpException(status, message)
}

// BadRequestException creates a 400 Bad Request exception.
func BadRequestException(message string) *HttpException {
	return common.NewBadRequestException(message)
}

// UnauthorizedException creates a 401 Unauthorized exception.
func UnauthorizedException(message string) *HttpException {
	return common.NewUnauthorizedException(message)
}

// ForbiddenException creates a 403 Forbidden exception.
func ForbiddenException(message string) *HttpException {
	return common.NewForbiddenException(message)
}

// NotFoundException creates a 404 Not Found exception.
func NotFoundException(message string) *HttpException {
	return common.NewNotFoundException(message)
}

// InternalServerErrorException creates a 500 Internal Server Error exception.
func InternalServerErrorException(message string) *HttpException {
	return common.NewInternalServerErrorException(message)
}

// ── Config & Logger modules ───────────────────────────────────────────────────

// ConfigModule is a ready-to-use module that registers and exports ConfigService.
// Import it in any module that needs environment variable access.
var ConfigModule = config.ConfigModule

// LogModule is a ready-to-use module that registers and exports LoggerService.
// Import it in any module that needs structured logging.
var LogModule = logger.LogModule

// ── WebSocket helpers ─────────────────────────────────────────────────────────

// WS creates a WebSocket route binding for the given path and handler.
// Use the returned WSRoute's fluent methods to add guards and versioning:
//
//	nexgou.WS("/chat", c.HandleChat).Guard(&AuthGuard{}).Version("v1")
func WS(path string, handler func(*WSContext) error) WSRoute {
	return nexgouws.NewRoute(path, nexgouws.Handler(handler))
}

// SSE creates an HTTP GET route that streams Server-Sent Events.
// The handler receives an *SSEContext and runs for the lifetime of the connection.
// Use the returned Route's fluent methods to add guards and versioning:
//
//	nexgou.SSE("/events", c.Stream).Guard(&AuthGuard{}).Version("v1")
func SSE(path string, handler func(*SSEContext) error) Route {
	return Route{
		Method:  "GET",
		Path:    path,
		Handler: nexgousse.ToHTTPHandler(nexgousse.HandlerFunc(handler)),
	}
}

// ── gRPC helpers ──────────────────────────────────────────────────────────────

// GRPC creates a GRPCRoute binding the given service descriptor to its
// implementation. Chain .Guard() and .Version() on the result as needed.
//
//	nexgou.GRPC(greeter.Greeter_ServiceDesc, &GreeterController{}).Guard(&AuthGuard{})
func GRPC(desc GRPCServiceDesc, impl any) GRPCRoute {
	return nexgougrpc.NewRoute(desc, impl)
}
